# THE FOLLOWING VARIABLES MUST BE BASH COMPLIANT
# DO NOT MODIFY FORMAT - ONLY VALUES
BATCH_SIZE=12
BLOCK_SIZE=64
MAX_ITERS=200
# THE BELOW VARIABLES DO NOT NEED TO BE BASH COMPLIANT
# YOU MAY FORMAT FOR USE IN PYTHON
EVAL_INTERVAL=100
LEARNING_RATE=3e-4
EVAL_ITERS=20
N_EMBD=128
N_HEAD=4
N_LAYER=4
DROPOUT=0.0
