# THE FOLLOWING VARIABLES MUST BE BASH COMPLIANT
# DO NOT MODIFY FORMAT - ONLY VALUES
# TODO: FIX MESSAGE
BATCH_SIZE=12
BLOCK_SIZE=64
MAX_ITERS=200
EVAL_INTERVAL=400
LEARNING_RATE=0.0003
EVAL_ITERS=20
N_EMBD=128
N_HEAD=4
N_LAYER=4
DROPOUT=0.0
