const BATCH_SIZE = 12 ;
const BLOCK_SIZE = 64 ;
const MAX_ITERS = 100 ;
const LEARNING_RATE = 0.0003 ;
const LOG_INTERVAL = 100 ;
const LOG_ITERS = 20 ;
const N_EMBD = 128 ;
const N_LAYER = 4 ;
const N_HEAD = 4 ;
const DROPOUT = 0.0 ;

// DO NOT MODIFY FORMATTING ABOVE THIS LINE
// N_EMBD, N_LAYER, N_HEAD, DROPOUT ONLY RELEVANT FOR GPT MODEL
export {
  BLOCK_SIZE,
  N_EMBD,
  N_LAYER,
  N_HEAD,
  DROPOUT
};
