name: Run evaluation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r torch numpy language_tool_python
    
    - name: Make script executable
      run: chmod +x eval/*.sh
      
    - name: Run evaluation script
      run: ./eval.sh
      working-directory: ./eval

    - name: Upload evaluation results
      uses: actions/upload-artifact@v4
      with:
        name: eval-results
        path: eval/*.txt
